export const FETCH_RECIPE_START = "FETCH_RECIPE_START";
export const FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCESS";
export const FETCH_RECIPE_FAIL = "FETCH_RECIPE_FAIL";
export const FETCH_RECIP_FAL = "FETCH_RECIP_FAL";